---
apiVersion: v1
kind: ConfigMap
metadata:
  name: guacamole-environment
data:
  MYSQL_HOSTNAME: 127.0.0.1
  MYSQL_ROOT_PASSWORD: xxxxx
  MYSQL_USER: guacamole_user
  MYSQL_DATABASE: guacamole_db
  MYSQL_PASSWORD: xxxx
  GUACAMOLE_HOME: /etc/guacamole
  GUACD_HOSTNAME: xxxx
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: guacamole
spec:
  containers:
  - name: mysql
    image: mysql
    restartPolicy: Always
    securityContext:
      seLinuxOptions:
        type: spc_t
    envFrom:
    - configMapRef:
        name: guacamole-environment
        optional: false
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
  - name: guacamole
    image: guacamole/guacamole
    restartPolicy: Always
    securityContext:
      seLinuxOptions:
        type: spc_t
    envFrom:
    - configMapRef:
        name: guacamole-environment
        optional: false
    ports:
    - containerPort: 8080
      hostPort: 8080
      protocol: tcp
      name: http
    volumeMounts:
    - mountPath: /etc/guacamole
      name: guacamole-config
  volumes:
  - name: mysql-data
    hostPath:
      path: /opt/mysql
      type: Directory
  - name: guacamole-config
    hostPath:
      path: /opt/guacamole
      type: Directory

