---
apiVersion: apps/v1
kind: Pod
metadata:
  name: guacd
spec:
  containers:
  - name: guacd
    image: guacamole/guacd
    restartPolicy: Always
    securityContext:
      seLinuxOptions:
        type: spc_t
    ports:
    - containerPort: 4822
      hostPort: 4822
      protocol: tcp
      name: guacd
